local_default: &local_default
  adapter: mysql
  host: localhost
  username: root
  password: 


development:
  database: ptnd_dev
  <<: *local_default

test: &test
  database: ptnd_test
  <<: *local_default
