development:
 api_key: 4913c83eb73716a7e6fcb85288ba362b
 secret_key: 18e9cdc10e7eea6e47eaba637b37339a
 canvas_page_name: ptndlol
 callback_url: http://ptnd.heroku.com/
 pretty_errors: true
 set_asset_host_to_callback_url: false

production:
 api_key: 4913c83eb73716a7e6fcb85288ba362b
 secret_key: 18e9cdc10e7eea6e47eaba637b37339a
 canvas_page_name: ptndlol
 callback_url: http://ptnd.heroku.com/
 pretty_errors: true
 set_asset_host_to_callback_url: false